#!/usr/bin/python3

print(f"{Fore.GREEN}{Style.BRIGHT} ____        ____    ____                                 ____{Style.RESET_ALL}")
time.sleep(0.1)
print(f"{Fore.GREEN}|    |      |    |  |    |                               |    |{Style.RESET_ALL}")
time.sleep(0.1)
print(f"{Fore.GREEN}|    |      |    |  |    |                               |    |{Style.RESET_ALL}")
time.sleep(0.1)
print(f"{Fore.GREEN}|    |      |    |  |    |             {Style.BRIGHT}___{Style.RESET_ALL}{Fore.GREEN}               |    |{Style.RESET_ALL}")
time.sleep(0.1)
print(f"{Fore.GREEN}|    |______|    |  |    |            |   | _______      |    |{Style.RESET_ALL}")
time.sleep(0.1)
print(f"{Fore.GREEN}|                |  |    |_______     |   |/       \     |    |_______{Style.RESET_ALL}")
time.sleep(0.1)
print(f"{Fore.GREEN}|     _______    |  |            \    |      ___    \    |            \ {Style.RESET_ALL}")
time.sleep(0.1)
print(f"{Fore.GREEN}|    |      |    |  |      __     \   |     /   \    \   |      __     \ {Style.RESET_ALL}")
time.sleep(0.1)
print(f"{Fore.GREEN}|    |      |    |  |     /  \     |  |    |     |    |  |     /  \     |{Style.RESET_ALL}")
time.sleep(0.1)
print(f"{Fore.GREEN}|    |      |    |  |     \__/     |  |    |     |    |  |     \__/     |{Style.RESET_ALL}")
time.sleep(0.1)
print(f"{Fore.GREEN}|    |      |    |  |             /   |    |     |    |  |             /{Style.RESET_ALL}")
time.sleep(0.1)
print(f"{Fore.GREEN}{Style.BRIGHT}|____|      |____|  |____________/    |____|     |____|  |____________/{Style.RESET_ALL}")
time.sleep(1.5)
print("\n\n")
print(f"{Fore.GREEN} *********************************************************************{Style.RESET_ALL}")
print("                        AirBnB_clone project")
print("                          The Console V1.0")
print("                     An Holberton School Project")
print(f"{Fore.GREEN}{Style.BRIGHT} *********************************************************************{Style.RESET_ALL}")
print("                                  By:")
print(f"{Style.BRIGHT} Nathan LAPEYRE (aka Pebkak)                               Simon BRARD{Style.RESET_ALL}")
print(f"{Fore.GREEN} *********************************************************************{Style.RESET_ALL}")
print("                                 2021")
print("\n\n")
